{
 "title": "Plex",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_sessions_active_count",
     "requestId": "Q-42ccdbaf-5caa-4ce6-9de6-1e885047bfa6-0A"
    }
   ]
  },
  {
   "title": "Transcoding",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_transcode_sessions_active_count",
     "requestId": "Q-42ccdbaf-5caa-4ce6-9de6-1e885047bfa6-0A"
    }
   ]
  },
  {
   "title": "Library",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_server_library_media_count",
     "requestId": "Q-42ccdbaf-5caa-4ce6-9de6-1e885047bfa6-0A"
    }
   ]
  }
 ]
}