apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plex_exporter.fullname" . }}
  labels:
{{ include "plex_exporter.labels" . | indent 4 }}
type: Opaque
stringData:
  config.json: |
    {
      "server": {
        "address": "{{ .Values.server.address }}",
        "port": {{ .Values.server.port }},
        "token": "{{ .Values.server.token }}"
      }
    }
