{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "plex_exporter.serviceAccountName" . }}
  labels:
{{ include "plex_exporter.labels" . | indent 4 }}
{{- end -}}
